from selenium.webdriver.common.by import By

class AuthLocators:
   """Локаторы страницы авторизации"""

   AUTH_NUMBER = (By.ID, "username")
   AUTH_EMAIL = (By.ID, "username")
   AUTH_LOGIN = (By.ID, "username")
   AUTH_LS = (By.ID, "username")
   AUTH_PASS = (By.ID, "password")
   AUTH_BTN = (By.ID, "kc-login")
   AUTH_ACTIVE_TAB = (By.CSS_SELECTOR, '.rt-tab.rt-tab--small.rt-tab--active')
   tub_phone = (By.ID, "t-btn-tab-phone")
   tub_mail = (By.ID, "t-btn-tab-mail")
   tub_login = (By.ID, "t-btn-tab-login")
   tub_personal_account = (By.ID, "t-btn-tab-ls")
   remember_me = (By.CLASS_NAME, "rt-checkbox__label")
   error_message = (By.XPATH, '//span[@id="form-error-message"]')
   authorization_form = (By.CLASS_NAME, "card-container__wrapper")
   menu_tub = (By.XPATH, "//div[@class='rt-tabs rt-tabs--orange rt-tabs--small tabs-input-container__tabs']")
   page_left = (By.ID, "page-left")
   page_right = (By.ID, "page-right")
   active_tub_phone = (By.XPATH, '//div[@id="t-btn-tab-phone" and @class="rt-tab rt-tab--small rt-tab--active"]')
   forgot_password = (By.ID, 'forgot_password')
   AUTH_FORM_ERROR = (By.XPATH, "//span[@id='form-error-message']")
   AUTH_FORGOT_PASSWORD = (By.ID, 'forgot_password')
   back_to_otp = (By.ID, 'back_to_otp_btn')
   register_link = (By.ID, 'kc-register')
   page_left_registration = (By.ID, 'page-left')
   page_right_registration = (By.ID, 'page-right')
   first_name = (By.NAME, 'firstName')
   last_name = (By.NAME, 'lastName')
   address_registration = (By.XPATH, "//*[contains(text(),'Регион')]")
   email_registration = (By.ID, 'address')
   password_registration = (By.ID, 'password')
   password_confirm = (By.ID, 'password-confirm')
   button_register = (By.NAME, 'register')
   registration_form = (By.CLASS_NAME, 'card-container__wrapper')
   name_card_container = (By.CLASS_NAME, 'card-container__title')
   new_password_container = (By.CLASS_NAME, 'new-password-container')
   error_account_exists = (By.XPATH, '//h2[text()="Учётная запись уже существует"]')
   button_exit = (By.NAME, 'gotoLogin')
   account_already_exists = (By.CLASS_NAME, 'card-modal__card-wrapper')
   button_restore_password = (By.ID, 'reg-err-reset-pass')
   button_register_confirm = (By.NAME, 'registration_confirm_btn')
   phone_confirmation = (By.CLASS_NAME, 'card-container__title')
   confirmation_code_email = (By.XPATH, "//div[@class='rt-sdi-container rt-sdi-container--medium']")
   button_receive_code = (By.CLASS_NAME, 'code-input-container__resend')
   code_container_timeout = (By.CLASS_NAME, 'code-input-container__timeout')
   button_change_email = (By.XPATH, "//button[@class='rt-link rt-link--orange register-confirm-form__back-btn']")
   privacy_policy = (By.CLASS_NAME, 'rt-footer-left__item-accent')
   footer = (By.ID, 'app-footer')
